{
  "flow_runs": [
    {
      "run_id": "efc1c569-a884-48eb-9daa-fee04f9255c2_0",
      "status": "Failed",
      "error": {
        "message": "Execution failure in 'Prepare_text_for_convertion': (Exception) StreamError(PermissionDenied(Some(AuthenticationError(\"ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.\\nAttempted credentials:\\n\\tEnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.\\nVisit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.\\n\\tManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.\\n\\tSharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.\\n\\tAzureCliCredential: Azure CLI not found on path\\n\\tAzurePowerShellCredential: Az.Account module >= 2.2.0 is not installed\\n\\tAzureDeveloperCliCredential: Azure Developer CLI could not be found. Please visit https://aka.ms/azure-dev for installation instructions and then,once installed, authenticate to your Azure account using 'azd auth login'.\\nTo mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.\"))))",
        "messageFormat": "Execution failure in '{node_name}'.",
        "messageParameters": {
          "node_name": "Prepare_text_for_convertion"
        },
        "referenceCode": "Tool/__pf_main__",
        "code": "UserError",
        "innerError": {
          "code": "ToolExecutionError",
          "innerError": null
        },
        "additionalInfo": [
          {
            "type": "ToolExecutionErrorDetails",
            "info": {
              "type": "Exception",
              "message": "StreamError(PermissionDenied(Some(AuthenticationError(\"ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.\\nAttempted credentials:\\n\\tEnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.\\nVisit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.\\n\\tManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.\\n\\tSharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.\\n\\tAzureCliCredential: Azure CLI not found on path\\n\\tAzurePowerShellCredential: Az.Account module >= 2.2.0 is not installed\\n\\tAzureDeveloperCliCredential: Azure Developer CLI could not be found. Please visit https://aka.ms/azure-dev for installation instructions and then,once installed, authenticate to your Azure account using 'azd auth login'.\\nTo mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.\"))))",
              "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\matse\\OneDrive\\peppsy\\prompt_flow\\peppsy_gpt\\Prepare_text_for_convertion.py\", line 10, in prepare_text_for_conversion\n    examples_pd = pd.read_excel(\"azureml://subscriptions/4a40333d-da0e-4cdb-8711-92dc11a1d1bd/resourcegroups/matsel-rg/workspaces/pepppsy/datastores/workspaceblobstore/paths/UI/2024-08-29_124003_UTC/Translated_Comments.xls\", usecols=columns)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\util\\_decorators.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\util\\_decorators.py\", line 331, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\io\\excel\\_base.py\", line 482, in read_excel\n    io = ExcelFile(io, storage_options=storage_options, engine=engine)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\io\\excel\\_base.py\", line 1652, in __init__\n    ext = inspect_excel_format(\n          ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\io\\excel\\_base.py\", line 1525, in inspect_excel_format\n    with get_handle(\n         ^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\io\\common.py\", line 713, in get_handle\n    ioargs = _get_filepath_or_buffer(\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\io\\common.py\", line 411, in _get_filepath_or_buffer\n    ).open()\n      ^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\fsspec\\core.py\", line 134, in open\n    return self.__enter__()\n           ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\fsspec\\core.py\", line 102, in __enter__\n    f = self.fs.open(self.path, mode=mode)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\fsspec\\asyn.py\", line 115, in wrapper\n    return sync(self.loop, func, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\fsspec\\asyn.py\", line 100, in sync\n    raise return_result\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\fsspec\\asyn.py\", line 55, in _runner\n    result[0] = await coro\n                ^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\azureml\\fsspec\\spec.py\", line 499, in _open\n    _reclassify_rslex_error(e)\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\azureml\\dataprep\\api\\mltable\\_validation_and_error_handler.py\", line 90, in _reclassify_rslex_error\n    raise err\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\azureml\\fsspec\\spec.py\", line 489, in _open\n    return si.open(buffering_options=BufferingOptions(64, downloader))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nException: StreamError(PermissionDenied(Some(AuthenticationError(\"ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.\\nAttempted credentials:\\n\\tEnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.\\nVisit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.\\n\\tManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.\\n\\tSharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.\\n\\tAzureCliCredential: Azure CLI not found on path\\n\\tAzurePowerShellCredential: Az.Account module >= 2.2.0 is not installed\\n\\tAzureDeveloperCliCredential: Azure Developer CLI could not be found. Please visit https://aka.ms/azure-dev for installation instructions and then,once installed, authenticate to your Azure account using 'azd auth login'.\\nTo mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.\"))))\n",
              "filename": "C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\azureml\\fsspec\\spec.py",
              "lineno": 489,
              "name": "_open"
            }
          }
        ],
        "debugInfo": {
          "type": "ToolExecutionError",
          "message": "Execution failure in 'Prepare_text_for_convertion': (Exception) StreamError(PermissionDenied(Some(AuthenticationError(\"ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.\\nAttempted credentials:\\n\\tEnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.\\nVisit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.\\n\\tManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.\\n\\tSharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.\\n\\tAzureCliCredential: Azure CLI not found on path\\n\\tAzurePowerShellCredential: Az.Account module >= 2.2.0 is not installed\\n\\tAzureDeveloperCliCredential: Azure Developer CLI could not be found. Please visit https://aka.ms/azure-dev for installation instructions and then,once installed, authenticate to your Azure account using 'azd auth login'.\\nTo mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.\"))))",
          "stackTrace": "\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\promptflow\\executor\\flow_executor.py\", line 889, in _exec\n    output, nodes_outputs = self._traverse_nodes(inputs, context)\n                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\promptflow\\executor\\flow_executor.py\", line 987, in _traverse_nodes\n    nodes_outputs, bypassed_nodes = self._submit_to_scheduler(context, inputs, batch_nodes)\n                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\promptflow\\executor\\flow_executor.py\", line 1013, in _submit_to_scheduler\n    ).execute(self._line_timeout_sec)\n      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\promptflow\\executor\\_flow_nodes_scheduler.py\", line 89, in execute\n    raise e\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\promptflow\\executor\\_flow_nodes_scheduler.py\", line 72, in execute\n    self._dag_manager.complete_nodes(self._collect_outputs(completed_futures))\n                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\promptflow\\executor\\_flow_nodes_scheduler.py\", line 113, in _collect_outputs\n    each_node_result = each_future.result()\n                       ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\concurrent\\futures\\_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\concurrent\\futures\\_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\concurrent\\futures\\thread.py\", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\promptflow\\executor\\_flow_nodes_scheduler.py\", line 134, in _exec_single_node_in_thread\n    result = context.invoke_tool(node, f, kwargs=kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\promptflow\\_core\\flow_execution_context.py\", line 88, in invoke_tool\n    result = self._invoke_tool_with_timer(node, f, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\promptflow\\_core\\flow_execution_context.py\", line 201, in _invoke_tool_with_timer\n    raise ToolExecutionError(node_name=node_name, module=module) from e\n",
          "innerException": {
            "type": "Exception",
            "message": "StreamError(PermissionDenied(Some(AuthenticationError(\"ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.\\nAttempted credentials:\\n\\tEnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.\\nVisit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.\\n\\tManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.\\n\\tSharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.\\n\\tAzureCliCredential: Azure CLI not found on path\\n\\tAzurePowerShellCredential: Az.Account module >= 2.2.0 is not installed\\n\\tAzureDeveloperCliCredential: Azure Developer CLI could not be found. Please visit https://aka.ms/azure-dev for installation instructions and then,once installed, authenticate to your Azure account using 'azd auth login'.\\nTo mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.\"))))",
            "stackTrace": "Traceback (most recent call last):\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\promptflow\\_core\\flow_execution_context.py\", line 190, in _invoke_tool_with_timer\n    return f(**kwargs)\n           ^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\promptflow\\_core\\tracer.py\", line 404, in wrapped\n    output = func(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\OneDrive\\peppsy\\prompt_flow\\peppsy_gpt\\Prepare_text_for_convertion.py\", line 10, in prepare_text_for_conversion\n    examples_pd = pd.read_excel(\"azureml://subscriptions/4a40333d-da0e-4cdb-8711-92dc11a1d1bd/resourcegroups/matsel-rg/workspaces/pepppsy/datastores/workspaceblobstore/paths/UI/2024-08-29_124003_UTC/Translated_Comments.xls\", usecols=columns)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\util\\_decorators.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\util\\_decorators.py\", line 331, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\io\\excel\\_base.py\", line 482, in read_excel\n    io = ExcelFile(io, storage_options=storage_options, engine=engine)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\io\\excel\\_base.py\", line 1652, in __init__\n    ext = inspect_excel_format(\n          ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\io\\excel\\_base.py\", line 1525, in inspect_excel_format\n    with get_handle(\n         ^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\io\\common.py\", line 713, in get_handle\n    ioargs = _get_filepath_or_buffer(\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\io\\common.py\", line 411, in _get_filepath_or_buffer\n    ).open()\n      ^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\fsspec\\core.py\", line 134, in open\n    return self.__enter__()\n           ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\fsspec\\core.py\", line 102, in __enter__\n    f = self.fs.open(self.path, mode=mode)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\fsspec\\asyn.py\", line 115, in wrapper\n    return sync(self.loop, func, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\fsspec\\asyn.py\", line 100, in sync\n    raise return_result\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\fsspec\\asyn.py\", line 55, in _runner\n    result[0] = await coro\n                ^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\azureml\\fsspec\\spec.py\", line 499, in _open\n    _reclassify_rslex_error(e)\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\azureml\\dataprep\\api\\mltable\\_validation_and_error_handler.py\", line 90, in _reclassify_rslex_error\n    raise err\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\azureml\\fsspec\\spec.py\", line 489, in _open\n    return si.open(buffering_options=BufferingOptions(64, downloader))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "innerException": null
          }
        }
      },
      "inputs": {
        "text": "Managed well over the holidays, but then experienced PMS. Cousin has been diagnosed with pulmonary fibrosis, read about it online, which caused significant anxiety and started a cycle of worrying thoughts. Couldn't find peace, had physical reactions, and concentration suffered. Went to work regardless, which was very difficult. Suspected severe PMS, agreed to increase Sertraline 7 days before the start of the cycle, otherwise treatment remains unchanged. Prescription issued, no indication of psychotic symptoms.",
        "example_size": 10,
        "text_to_be_converted": 9,
        "system_prompt": "make text easier to understand"
      },
      "output": null,
      "metrics": null,
      "request": null,
      "parent_run_id": "efc1c569-a884-48eb-9daa-fee04f9255c2",
      "root_run_id": "efc1c569-a884-48eb-9daa-fee04f9255c2",
      "source_run_id": null,
      "flow_id": "template_standard_flow",
      "start_time": "2024-11-29T10:05:40.403600Z",
      "end_time": "2024-11-29T10:05:48.441737Z",
      "index": 0,
      "api_calls": [
        {
          "name": "flow",
          "node_name": "flow",
          "type": "Flow",
          "start_time": 1732871140.4036,
          "end_time": 1732871148.441737,
          "children": [
            {
              "name": "prepare_examples",
              "type": "Tool",
              "inputs": {
                "example_size": 10
              },
              "output": null,
              "start_time": 1732871140.406599,
              "end_time": 1732871148.406235,
              "error": {
                "message": "StreamError(PermissionDenied(Some(AuthenticationError(\"ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.\\nAttempted credentials:\\n\\tEnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.\\nVisit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.\\n\\tManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.\\n\\tSharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.\\n\\tAzureCliCredential: Azure CLI not found on path\\n\\tAzurePowerShellCredential: Az.Account module >= 2.2.0 is not installed\\n\\tAzureDeveloperCliCredential: Azure Developer CLI could not be found. Please visit https://aka.ms/azure-dev for installation instructions and then,once installed, authenticate to your Azure account using 'azd auth login'.\\nTo mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.\"))))",
                "type": "Exception"
              },
              "children": [],
              "node_name": "prepare_examples",
              "parent_id": "",
              "id": "38d257b2-fafa-4f62-91a9-b797907df6cb",
              "system_metrics": {}
            },
            {
              "name": "prepare_text_for_conversion",
              "type": "Tool",
              "inputs": {
                "num": 9,
                "tekst": "Managed well over the holidays, but then experienced PMS. Cousin has been diagnosed with pulmonary fibrosis, read about it online, which caused significant anxiety and started a cycle of worrying thoughts. Couldn't find peace, had physical reactions, and concentration suffered. Went to work regardless, which was very difficult. Suspected severe PMS, agreed to increase Sertraline 7 days before the start of the cycle, otherwise treatment remains unchanged. Prescription issued, no indication of psychotic symptoms."
              },
              "output": null,
              "start_time": 1732871140.406599,
              "end_time": 1732871146.967971,
              "error": {
                "message": "StreamError(PermissionDenied(Some(AuthenticationError(\"ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.\\nAttempted credentials:\\n\\tEnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.\\nVisit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.\\n\\tManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.\\n\\tSharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.\\n\\tAzureCliCredential: Azure CLI not found on path\\n\\tAzurePowerShellCredential: Az.Account module >= 2.2.0 is not installed\\n\\tAzureDeveloperCliCredential: Azure Developer CLI could not be found. Please visit https://aka.ms/azure-dev for installation instructions and then,once installed, authenticate to your Azure account using 'azd auth login'.\\nTo mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.\"))))",
                "type": "Exception"
              },
              "children": [],
              "node_name": "Prepare_text_for_convertion",
              "parent_id": "",
              "id": "1dc3014c-cc8f-4872-973b-af13c5de9159",
              "system_metrics": {}
            }
          ],
          "system_metrics": {
            "duration": 8.038137,
            "prompt_tokens": 0,
            "completion_tokens": 0,
            "total_tokens": 0
          }
        }
      ],
      "variant_id": "",
      "name": "",
      "description": "",
      "tags": null,
      "system_metrics": {
        "duration": 8.038137,
        "prompt_tokens": 0,
        "completion_tokens": 0,
        "total_tokens": 0
      },
      "result": null,
      "upload_metrics": false
    }
  ],
  "node_runs": [
    {
      "node": "prepare_examples",
      "flow_run_id": "efc1c569-a884-48eb-9daa-fee04f9255c2",
      "run_id": "efc1c569-a884-48eb-9daa-fee04f9255c2_prepare_examples_0",
      "status": "Failed",
      "inputs": {
        "example_size": 10
      },
      "output": null,
      "metrics": null,
      "error": {
        "message": "Execution failure in 'prepare_examples': (Exception) StreamError(PermissionDenied(Some(AuthenticationError(\"ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.\\nAttempted credentials:\\n\\tEnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.\\nVisit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.\\n\\tManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.\\n\\tSharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.\\n\\tAzureCliCredential: Azure CLI not found on path\\n\\tAzurePowerShellCredential: Az.Account module >= 2.2.0 is not installed\\n\\tAzureDeveloperCliCredential: Azure Developer CLI could not be found. Please visit https://aka.ms/azure-dev for installation instructions and then,once installed, authenticate to your Azure account using 'azd auth login'.\\nTo mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.\"))))",
        "messageFormat": "Execution failure in '{node_name}'.",
        "messageParameters": {
          "node_name": "prepare_examples"
        },
        "referenceCode": "Tool/__pf_main__",
        "code": "UserError",
        "innerError": {
          "code": "ToolExecutionError",
          "innerError": null
        },
        "additionalInfo": [
          {
            "type": "ToolExecutionErrorDetails",
            "info": {
              "type": "Exception",
              "message": "StreamError(PermissionDenied(Some(AuthenticationError(\"ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.\\nAttempted credentials:\\n\\tEnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.\\nVisit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.\\n\\tManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.\\n\\tSharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.\\n\\tAzureCliCredential: Azure CLI not found on path\\n\\tAzurePowerShellCredential: Az.Account module >= 2.2.0 is not installed\\n\\tAzureDeveloperCliCredential: Azure Developer CLI could not be found. Please visit https://aka.ms/azure-dev for installation instructions and then,once installed, authenticate to your Azure account using 'azd auth login'.\\nTo mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.\"))))",
              "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\matse\\OneDrive\\peppsy\\prompt_flow\\peppsy_gpt\\prepare_examples.py\", line 19, in prepare_examples\n    examples_pd = pd.read_excel(\"azureml://subscriptions/4a40333d-da0e-4cdb-8711-92dc11a1d1bd/resourcegroups/matsel-rg/workspaces/pepppsy/datastores/workspaceblobstore/paths/UI/2024-08-29_124003_UTC/Translated_Comments.xls\", usecols=columns)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\util\\_decorators.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\util\\_decorators.py\", line 331, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\io\\excel\\_base.py\", line 482, in read_excel\n    io = ExcelFile(io, storage_options=storage_options, engine=engine)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\io\\excel\\_base.py\", line 1652, in __init__\n    ext = inspect_excel_format(\n          ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\io\\excel\\_base.py\", line 1525, in inspect_excel_format\n    with get_handle(\n         ^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\io\\common.py\", line 713, in get_handle\n    ioargs = _get_filepath_or_buffer(\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\io\\common.py\", line 411, in _get_filepath_or_buffer\n    ).open()\n      ^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\fsspec\\core.py\", line 134, in open\n    return self.__enter__()\n           ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\fsspec\\core.py\", line 102, in __enter__\n    f = self.fs.open(self.path, mode=mode)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\fsspec\\asyn.py\", line 115, in wrapper\n    return sync(self.loop, func, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\fsspec\\asyn.py\", line 100, in sync\n    raise return_result\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\fsspec\\asyn.py\", line 55, in _runner\n    result[0] = await coro\n                ^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\azureml\\fsspec\\spec.py\", line 499, in _open\n    _reclassify_rslex_error(e)\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\azureml\\dataprep\\api\\mltable\\_validation_and_error_handler.py\", line 90, in _reclassify_rslex_error\n    raise err\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\azureml\\fsspec\\spec.py\", line 489, in _open\n    return si.open(buffering_options=BufferingOptions(64, downloader))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nException: StreamError(PermissionDenied(Some(AuthenticationError(\"ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.\\nAttempted credentials:\\n\\tEnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.\\nVisit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.\\n\\tManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.\\n\\tSharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.\\n\\tAzureCliCredential: Azure CLI not found on path\\n\\tAzurePowerShellCredential: Az.Account module >= 2.2.0 is not installed\\n\\tAzureDeveloperCliCredential: Azure Developer CLI could not be found. Please visit https://aka.ms/azure-dev for installation instructions and then,once installed, authenticate to your Azure account using 'azd auth login'.\\nTo mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.\"))))\n",
              "filename": "C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\azureml\\fsspec\\spec.py",
              "lineno": 489,
              "name": "_open"
            }
          }
        ],
        "debugInfo": {
          "type": "ToolExecutionError",
          "message": "Execution failure in 'prepare_examples': (Exception) StreamError(PermissionDenied(Some(AuthenticationError(\"ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.\\nAttempted credentials:\\n\\tEnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.\\nVisit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.\\n\\tManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.\\n\\tSharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.\\n\\tAzureCliCredential: Azure CLI not found on path\\n\\tAzurePowerShellCredential: Az.Account module >= 2.2.0 is not installed\\n\\tAzureDeveloperCliCredential: Azure Developer CLI could not be found. Please visit https://aka.ms/azure-dev for installation instructions and then,once installed, authenticate to your Azure account using 'azd auth login'.\\nTo mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.\"))))",
          "stackTrace": "\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\promptflow\\_core\\flow_execution_context.py\", line 88, in invoke_tool\n    result = self._invoke_tool_with_timer(node, f, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\promptflow\\_core\\flow_execution_context.py\", line 201, in _invoke_tool_with_timer\n    raise ToolExecutionError(node_name=node_name, module=module) from e\n",
          "innerException": {
            "type": "Exception",
            "message": "StreamError(PermissionDenied(Some(AuthenticationError(\"ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.\\nAttempted credentials:\\n\\tEnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.\\nVisit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.\\n\\tManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.\\n\\tSharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.\\n\\tAzureCliCredential: Azure CLI not found on path\\n\\tAzurePowerShellCredential: Az.Account module >= 2.2.0 is not installed\\n\\tAzureDeveloperCliCredential: Azure Developer CLI could not be found. Please visit https://aka.ms/azure-dev for installation instructions and then,once installed, authenticate to your Azure account using 'azd auth login'.\\nTo mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.\"))))",
            "stackTrace": "Traceback (most recent call last):\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\promptflow\\_core\\flow_execution_context.py\", line 190, in _invoke_tool_with_timer\n    return f(**kwargs)\n           ^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\promptflow\\_core\\tracer.py\", line 404, in wrapped\n    output = func(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\OneDrive\\peppsy\\prompt_flow\\peppsy_gpt\\prepare_examples.py\", line 19, in prepare_examples\n    examples_pd = pd.read_excel(\"azureml://subscriptions/4a40333d-da0e-4cdb-8711-92dc11a1d1bd/resourcegroups/matsel-rg/workspaces/pepppsy/datastores/workspaceblobstore/paths/UI/2024-08-29_124003_UTC/Translated_Comments.xls\", usecols=columns)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\util\\_decorators.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\util\\_decorators.py\", line 331, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\io\\excel\\_base.py\", line 482, in read_excel\n    io = ExcelFile(io, storage_options=storage_options, engine=engine)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\io\\excel\\_base.py\", line 1652, in __init__\n    ext = inspect_excel_format(\n          ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\io\\excel\\_base.py\", line 1525, in inspect_excel_format\n    with get_handle(\n         ^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\io\\common.py\", line 713, in get_handle\n    ioargs = _get_filepath_or_buffer(\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\io\\common.py\", line 411, in _get_filepath_or_buffer\n    ).open()\n      ^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\fsspec\\core.py\", line 134, in open\n    return self.__enter__()\n           ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\fsspec\\core.py\", line 102, in __enter__\n    f = self.fs.open(self.path, mode=mode)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\fsspec\\asyn.py\", line 115, in wrapper\n    return sync(self.loop, func, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\fsspec\\asyn.py\", line 100, in sync\n    raise return_result\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\fsspec\\asyn.py\", line 55, in _runner\n    result[0] = await coro\n                ^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\azureml\\fsspec\\spec.py\", line 499, in _open\n    _reclassify_rslex_error(e)\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\azureml\\dataprep\\api\\mltable\\_validation_and_error_handler.py\", line 90, in _reclassify_rslex_error\n    raise err\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\azureml\\fsspec\\spec.py\", line 489, in _open\n    return si.open(buffering_options=BufferingOptions(64, downloader))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "innerException": null
          }
        }
      },
      "parent_run_id": "efc1c569-a884-48eb-9daa-fee04f9255c2_0",
      "start_time": "2024-11-29T10:05:40.405599Z",
      "end_time": "2024-11-29T10:05:48.430326Z",
      "index": 0,
      "api_calls": [
        {
          "name": "prepare_examples",
          "type": "Tool",
          "inputs": {
            "example_size": 10
          },
          "output": null,
          "start_time": 1732871140.406599,
          "end_time": 1732871148.406235,
          "error": {
            "message": "StreamError(PermissionDenied(Some(AuthenticationError(\"ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.\\nAttempted credentials:\\n\\tEnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.\\nVisit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.\\n\\tManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.\\n\\tSharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.\\n\\tAzureCliCredential: Azure CLI not found on path\\n\\tAzurePowerShellCredential: Az.Account module >= 2.2.0 is not installed\\n\\tAzureDeveloperCliCredential: Azure Developer CLI could not be found. Please visit https://aka.ms/azure-dev for installation instructions and then,once installed, authenticate to your Azure account using 'azd auth login'.\\nTo mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.\"))))",
            "type": "Exception"
          },
          "children": [],
          "node_name": "prepare_examples",
          "parent_id": "",
          "id": "38d257b2-fafa-4f62-91a9-b797907df6cb",
          "system_metrics": {}
        }
      ],
      "variant_id": "",
      "cached_run_id": null,
      "cached_flow_run_id": null,
      "logs": {
        "stdout": "",
        "stderr": "[2024-11-29T10:05:48+0000] DefaultAzureCredential failed to retrieve a token from the included credentials.\nAttempted credentials:\n\tEnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.\nVisit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.\n\tManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.\n\tSharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.\n\tAzureCliCredential: Azure CLI not found on path\n\tAzurePowerShellCredential: Az.Account module >= 2.2.0 is not installed\n\tAzureDeveloperCliCredential: Azure Developer CLI could not be found. Please visit https://aka.ms/azure-dev for installation instructions and then,once installed, authenticate to your Azure account using 'azd auth login'.\nTo mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.\n"
      },
      "system_metrics": {
        "duration": 8.024727
      },
      "result": null
    },
    {
      "node": "Prepare_text_for_convertion",
      "flow_run_id": "efc1c569-a884-48eb-9daa-fee04f9255c2",
      "run_id": "efc1c569-a884-48eb-9daa-fee04f9255c2_Prepare_text_for_convertion_0",
      "status": "Failed",
      "inputs": {
        "num": 9,
        "tekst": "Managed well over the holidays, but then experienced PMS. Cousin has been diagnosed with pulmonary fibrosis, read about it online, which caused significant anxiety and started a cycle of worrying thoughts. Couldn't find peace, had physical reactions, and concentration suffered. Went to work regardless, which was very difficult. Suspected severe PMS, agreed to increase Sertraline 7 days before the start of the cycle, otherwise treatment remains unchanged. Prescription issued, no indication of psychotic symptoms."
      },
      "output": null,
      "metrics": null,
      "error": {
        "message": "Execution failure in 'Prepare_text_for_convertion': (Exception) StreamError(PermissionDenied(Some(AuthenticationError(\"ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.\\nAttempted credentials:\\n\\tEnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.\\nVisit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.\\n\\tManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.\\n\\tSharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.\\n\\tAzureCliCredential: Azure CLI not found on path\\n\\tAzurePowerShellCredential: Az.Account module >= 2.2.0 is not installed\\n\\tAzureDeveloperCliCredential: Azure Developer CLI could not be found. Please visit https://aka.ms/azure-dev for installation instructions and then,once installed, authenticate to your Azure account using 'azd auth login'.\\nTo mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.\"))))",
        "messageFormat": "Execution failure in '{node_name}'.",
        "messageParameters": {
          "node_name": "Prepare_text_for_convertion"
        },
        "referenceCode": "Tool/__pf_main__",
        "code": "UserError",
        "innerError": {
          "code": "ToolExecutionError",
          "innerError": null
        },
        "additionalInfo": [
          {
            "type": "ToolExecutionErrorDetails",
            "info": {
              "type": "Exception",
              "message": "StreamError(PermissionDenied(Some(AuthenticationError(\"ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.\\nAttempted credentials:\\n\\tEnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.\\nVisit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.\\n\\tManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.\\n\\tSharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.\\n\\tAzureCliCredential: Azure CLI not found on path\\n\\tAzurePowerShellCredential: Az.Account module >= 2.2.0 is not installed\\n\\tAzureDeveloperCliCredential: Azure Developer CLI could not be found. Please visit https://aka.ms/azure-dev for installation instructions and then,once installed, authenticate to your Azure account using 'azd auth login'.\\nTo mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.\"))))",
              "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\matse\\OneDrive\\peppsy\\prompt_flow\\peppsy_gpt\\Prepare_text_for_convertion.py\", line 10, in prepare_text_for_conversion\n    examples_pd = pd.read_excel(\"azureml://subscriptions/4a40333d-da0e-4cdb-8711-92dc11a1d1bd/resourcegroups/matsel-rg/workspaces/pepppsy/datastores/workspaceblobstore/paths/UI/2024-08-29_124003_UTC/Translated_Comments.xls\", usecols=columns)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\util\\_decorators.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\util\\_decorators.py\", line 331, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\io\\excel\\_base.py\", line 482, in read_excel\n    io = ExcelFile(io, storage_options=storage_options, engine=engine)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\io\\excel\\_base.py\", line 1652, in __init__\n    ext = inspect_excel_format(\n          ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\io\\excel\\_base.py\", line 1525, in inspect_excel_format\n    with get_handle(\n         ^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\io\\common.py\", line 713, in get_handle\n    ioargs = _get_filepath_or_buffer(\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\io\\common.py\", line 411, in _get_filepath_or_buffer\n    ).open()\n      ^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\fsspec\\core.py\", line 134, in open\n    return self.__enter__()\n           ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\fsspec\\core.py\", line 102, in __enter__\n    f = self.fs.open(self.path, mode=mode)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\fsspec\\asyn.py\", line 115, in wrapper\n    return sync(self.loop, func, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\fsspec\\asyn.py\", line 100, in sync\n    raise return_result\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\fsspec\\asyn.py\", line 55, in _runner\n    result[0] = await coro\n                ^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\azureml\\fsspec\\spec.py\", line 499, in _open\n    _reclassify_rslex_error(e)\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\azureml\\dataprep\\api\\mltable\\_validation_and_error_handler.py\", line 90, in _reclassify_rslex_error\n    raise err\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\azureml\\fsspec\\spec.py\", line 489, in _open\n    return si.open(buffering_options=BufferingOptions(64, downloader))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nException: StreamError(PermissionDenied(Some(AuthenticationError(\"ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.\\nAttempted credentials:\\n\\tEnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.\\nVisit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.\\n\\tManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.\\n\\tSharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.\\n\\tAzureCliCredential: Azure CLI not found on path\\n\\tAzurePowerShellCredential: Az.Account module >= 2.2.0 is not installed\\n\\tAzureDeveloperCliCredential: Azure Developer CLI could not be found. Please visit https://aka.ms/azure-dev for installation instructions and then,once installed, authenticate to your Azure account using 'azd auth login'.\\nTo mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.\"))))\n",
              "filename": "C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\azureml\\fsspec\\spec.py",
              "lineno": 489,
              "name": "_open"
            }
          }
        ],
        "debugInfo": {
          "type": "ToolExecutionError",
          "message": "Execution failure in 'Prepare_text_for_convertion': (Exception) StreamError(PermissionDenied(Some(AuthenticationError(\"ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.\\nAttempted credentials:\\n\\tEnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.\\nVisit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.\\n\\tManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.\\n\\tSharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.\\n\\tAzureCliCredential: Azure CLI not found on path\\n\\tAzurePowerShellCredential: Az.Account module >= 2.2.0 is not installed\\n\\tAzureDeveloperCliCredential: Azure Developer CLI could not be found. Please visit https://aka.ms/azure-dev for installation instructions and then,once installed, authenticate to your Azure account using 'azd auth login'.\\nTo mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.\"))))",
          "stackTrace": "\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\promptflow\\_core\\flow_execution_context.py\", line 88, in invoke_tool\n    result = self._invoke_tool_with_timer(node, f, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\promptflow\\_core\\flow_execution_context.py\", line 201, in _invoke_tool_with_timer\n    raise ToolExecutionError(node_name=node_name, module=module) from e\n",
          "innerException": {
            "type": "Exception",
            "message": "StreamError(PermissionDenied(Some(AuthenticationError(\"ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.\\nAttempted credentials:\\n\\tEnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.\\nVisit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.\\n\\tManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.\\n\\tSharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.\\n\\tAzureCliCredential: Azure CLI not found on path\\n\\tAzurePowerShellCredential: Az.Account module >= 2.2.0 is not installed\\n\\tAzureDeveloperCliCredential: Azure Developer CLI could not be found. Please visit https://aka.ms/azure-dev for installation instructions and then,once installed, authenticate to your Azure account using 'azd auth login'.\\nTo mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.\"))))",
            "stackTrace": "Traceback (most recent call last):\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\promptflow\\_core\\flow_execution_context.py\", line 190, in _invoke_tool_with_timer\n    return f(**kwargs)\n           ^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\promptflow\\_core\\tracer.py\", line 404, in wrapped\n    output = func(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\OneDrive\\peppsy\\prompt_flow\\peppsy_gpt\\Prepare_text_for_convertion.py\", line 10, in prepare_text_for_conversion\n    examples_pd = pd.read_excel(\"azureml://subscriptions/4a40333d-da0e-4cdb-8711-92dc11a1d1bd/resourcegroups/matsel-rg/workspaces/pepppsy/datastores/workspaceblobstore/paths/UI/2024-08-29_124003_UTC/Translated_Comments.xls\", usecols=columns)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\util\\_decorators.py\", line 211, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\util\\_decorators.py\", line 331, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\io\\excel\\_base.py\", line 482, in read_excel\n    io = ExcelFile(io, storage_options=storage_options, engine=engine)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\io\\excel\\_base.py\", line 1652, in __init__\n    ext = inspect_excel_format(\n          ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\io\\excel\\_base.py\", line 1525, in inspect_excel_format\n    with get_handle(\n         ^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\io\\common.py\", line 713, in get_handle\n    ioargs = _get_filepath_or_buffer(\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\io\\common.py\", line 411, in _get_filepath_or_buffer\n    ).open()\n      ^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\fsspec\\core.py\", line 134, in open\n    return self.__enter__()\n           ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\fsspec\\core.py\", line 102, in __enter__\n    f = self.fs.open(self.path, mode=mode)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\fsspec\\asyn.py\", line 115, in wrapper\n    return sync(self.loop, func, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\fsspec\\asyn.py\", line 100, in sync\n    raise return_result\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\fsspec\\asyn.py\", line 55, in _runner\n    result[0] = await coro\n                ^^^^^^^^^^\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\azureml\\fsspec\\spec.py\", line 499, in _open\n    _reclassify_rslex_error(e)\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\azureml\\dataprep\\api\\mltable\\_validation_and_error_handler.py\", line 90, in _reclassify_rslex_error\n    raise err\n  File \"C:\\Users\\matse\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\azureml\\fsspec\\spec.py\", line 489, in _open\n    return si.open(buffering_options=BufferingOptions(64, downloader))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "innerException": null
          }
        }
      },
      "parent_run_id": "efc1c569-a884-48eb-9daa-fee04f9255c2_0",
      "start_time": "2024-11-29T10:05:40.406599Z",
      "end_time": "2024-11-29T10:05:47.003781Z",
      "index": 0,
      "api_calls": [
        {
          "name": "prepare_text_for_conversion",
          "type": "Tool",
          "inputs": {
            "num": 9,
            "tekst": "Managed well over the holidays, but then experienced PMS. Cousin has been diagnosed with pulmonary fibrosis, read about it online, which caused significant anxiety and started a cycle of worrying thoughts. Couldn't find peace, had physical reactions, and concentration suffered. Went to work regardless, which was very difficult. Suspected severe PMS, agreed to increase Sertraline 7 days before the start of the cycle, otherwise treatment remains unchanged. Prescription issued, no indication of psychotic symptoms."
          },
          "output": null,
          "start_time": 1732871140.406599,
          "end_time": 1732871146.967971,
          "error": {
            "message": "StreamError(PermissionDenied(Some(AuthenticationError(\"ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.\\nAttempted credentials:\\n\\tEnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.\\nVisit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.\\n\\tManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.\\n\\tSharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.\\n\\tAzureCliCredential: Azure CLI not found on path\\n\\tAzurePowerShellCredential: Az.Account module >= 2.2.0 is not installed\\n\\tAzureDeveloperCliCredential: Azure Developer CLI could not be found. Please visit https://aka.ms/azure-dev for installation instructions and then,once installed, authenticate to your Azure account using 'azd auth login'.\\nTo mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.\"))))",
            "type": "Exception"
          },
          "children": [],
          "node_name": "Prepare_text_for_convertion",
          "parent_id": "",
          "id": "1dc3014c-cc8f-4872-973b-af13c5de9159",
          "system_metrics": {}
        }
      ],
      "variant_id": "",
      "cached_run_id": null,
      "cached_flow_run_id": null,
      "logs": {
        "stdout": "",
        "stderr": "[2024-11-29T10:05:46+0000] DefaultAzureCredential failed to retrieve a token from the included credentials.\nAttempted credentials:\n\tEnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.\nVisit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.\n\tManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.\n\tSharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.\n\tAzureCliCredential: Azure CLI not found on path\n\tAzurePowerShellCredential: Az.Account module >= 2.2.0 is not installed\n\tAzureDeveloperCliCredential: Azure Developer CLI could not be found. Please visit https://aka.ms/azure-dev for installation instructions and then,once installed, authenticate to your Azure account using 'azd auth login'.\nTo mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.\n"
      },
      "system_metrics": {
        "duration": 6.597182
      },
      "result": null
    }
  ]
}